services:
  postgres:
    image: "postgres:17.5-alpine"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB}"
    volumes:
      - "./temp/postgresdata:/var/lib/postgresql/data"