services:
  postgres:
    image: "postgres:17.5-alpine"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB}"
    volumes:
      - "./temp/postgresdata:/var/lib/postgresql/data"
  python-backend:
    image: python:3.9.22-alpine3.22
    build:
      context: ./backend/python
      dockerfile: ./Dockerfile
    ports:
      - "20701:20701"
    environment:
      - PORT=20701
    volumes:
      - ./backend/python/src:/usr/src