services:
  postgres:
    image: "postgres:17.5-alpine"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB}"
    volumes:
      - "./temp/postgresdata:/var/lib/postgresql/data"
  python-backend:
    build:
      context: ./backend/python
      dockerfile: ./Dockerfile
    ports:
      - "20701:20701"
    environment:
      - FLASK_PORT=20701
    volumes:
      - ./backend/python/src:/usr/src
  react-frontend:
    build:
      context: ./frontend/react
      dockerfile: ./Dockerfile
    ports:
      - "20710:20710"
    environment:
      - PORT=20710
    volumes:
      - ./frontend/react/src:/usr/src